// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqehkbgaumjzbhxvsbqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxZWhrYmdhdW1qemJoeHZzYnFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NjMxOTMsImV4cCI6MjA2MTAzOTE5M30.NyhP3QO5a8QVVY7DlzUVThRWT5lRX1DojoB5oxIInxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);